export default [
    require('../assets/cards/card0.png'),
    require('../assets/cards/card1.png'),
    require('../assets/cards/card2.png'),
    require('../assets/cards/card3.png'),
    require('../assets/cards/card4.png'),
    require('../assets/cards/card5.png'),
    require('../assets/cards/card6.png'),
    require('../assets/cards/card7.png'),
    require('../assets/cards/card8.png'),
    require('../assets/cards/card9.png'),
    require('../assets/cards/card10.png'),
    require('../assets/cards/card11.png'),
    require('../assets/cards/card12.png'),
    require('../assets/cards/card13.png'),
    require('../assets/cards/card14.png'),
    require('../assets/cards/card15.png'),
    require('../assets/cards/card16.png'),
    require('../assets/cards/card17.png'),
    require('../assets/cards/card18.png'),
    require('../assets/cards/card19.png'),
    require('../assets/cards/card20.png'),
    require('../assets/cards/card21.png'),
    require('../assets/cards/card22.png'),
    require('../assets/cards/card23.png'),
    require('../assets/cards/card24.png'),
  ];
  